server:
  port: 9001

spring:
  application:
    name:USER-SERVICE
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serive-url:
      defaultzone: localhost:8761/eureka

  instance:
    hostname: localhost
